info:
  contact: {}
paths:
  /pexel:
    post:
      consumes:
      - application/json
      description: Get an image from pexels
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: colosach pexels
      tags:
      - example
swagger: "2.0"
